### ISSUE TITLE
Delete branches based on regex

### ISSUE THREAD

**Issue by emmahsax** [dawidd6/action-delete-branch#8]
Is it possible to use the prefix or something, so that we can delete all branches that start with certain characters or end with certain characters?

But even when I pass in the exact branch name, it still refuses to delete the branch at all.

**Comment by dawidd6** [comment]
This Action does not support regex pattern matching, but I think it could be a good feature and I would accept a PR for that.

**Comment by emmahsax** [comment]
I'm closing this issue because I'd like to clean up my Open Issues list. I still think this would be a valuable feature, but my use-case for it has gone down dramatically, so I don't feel the need at the moment to contribute to it. Thanks for looking at it though! Feel free to reopen this issue if it's needed further down the line.
